
FROM ubuntu:latest

# instalar ferreamentas de teste de rede

RUN apt update 

RUN apt upgrade -y 

RUN apt install -y net-tools dnsutils iputils-ping


# criar imagem docker 
    # docker build -t my-image .

# criar container 
    # docker run -it --name my-container my-image

#criar rede 
    # docker network create -d bridge net-ubuntu